name: release

on:
  workflow_dispatch:
    inputs:
      github-token:
        description: 'Github token to use'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
        uses: actions/checkout@v2
        with:
          repository: nearform/bench-board-good-first-issues
          token: ${{ secrets.github-token }} # `GH_PAT` is a secret that contains your PAT
          path: good-first-issues
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - uses: actions/github-script@v6
        with:
          github-token: ${{ inputs.github-token }}
          script: |
            const script = require('${{ github.action_path }}/good-first-issues/index.js')
            await script({ github, context, inputs: ${{ toJSON({
              organizations: 'sameer-org',
              timeInterval: '10 days',
              projectId: 'PN_kwDOBfteDc4AA3N5',
              token: '${{ inputs.github-token }}'
            }) }} })
